url: http://0.0.0.0:4000 #
baseurl:
# Site settings
title: NJU | 袁增伟教授课题组
email: #
description: "欢迎来到袁增伟教授课题组，我们专注于物质循环及其资源环境效益研究。"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1a8a4c
  secondary: 1aaa4c
  secondary-dark: 111
  navheader-color: 1a6a4c
  navbar-color: f7f7f7
  labname-color: f2ecde
# duoshuo
duoshuo_username:   sceenju
duoshuo_share:      false

#重要事件
pic:
  - title1: Slide 1 Title
    subtitle1: "这是第一个描述"
    url1: #
    img1: img/img-1.jpg
  - title2: Slide 2 Title
    subtitle2: "这是第二个描述"
    url2: #
    img2: img/img-2.jpg
  - title3: Slide 3 Title
    subtitle3: "这是第三个描述"
    url3: #
    img3: img/img-3.jpg
  - title4: Slide 4 Title
    subtitle4: "这是第四个描述"
    url4: #
    img4: img/img-4.jpg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: google-plus
    url: #
  - title: github
    url: https://github.com/sceenju
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 栖霞区仙林大道163号南京大学仙林校区环境学院
  - line: 中国江苏省南京市

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  syntax_highlighter: rouge
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
