url: https://sceenju.github.io
baseurl:
# Site settings
title: NJU | 袁增伟教授课题组
email: #
description: "欢迎来到袁增伟教授课题组，我们专注于物质循环及其资源环境效益研究。"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1a8a4c
  secondary: 1aaa4c
  secondary-dark: 111
  navheader-color: 1a6a4c
  navbar-color: f7f7f7
  labname-color: f2ecde
# duoshuo
duoshuo_username:   sceenju
duoshuo_share:      false


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: google-plus
    url: #
  - title: github
    url: https://github.com/sceenju
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 栖霞区仙林大道163号南京大学仙林校区环境学院
  - line: 中国江苏省南京市

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
